services:
  minio:
    container_name: minio

    build:
      context: minio
      dockerfile: Dockerfile

    ports:
      - '49000:9000'
      - '49001:9001'

    environment:
      - MINIO_ROOT_USER=miniroot
      - MINIO_ROOT_PASSWORD=miniroot
      - MINIO_DEFAULT_BUCKETS='users,groups,posts'
    
    command: 
      minio server ~/minio --address "10.5.0.2:9000" --console-address "10.5.0.2:9001"
    
    volumes:
      - minio-vol:/data

    networks:
      _net:
        ipv4_address: 10.5.0.2

  api:
    depends_on:
      - api_db
    container_name: api

    build:
      context: api
      dockerfile: Dockerfile

    ports:
      - '59000:8080'
    
    networks:
      _net:
        ipv4_address: 10.5.0.3

  api_db:
    container_name: api_db

    image: mysql:latest
    
    restart: always
    
    environment:
      MYSQL_DATABASE: vybe
      MYSQL_ROOT_PASSWORD: root

    command:
      '--bind-address=10.5.0.4'

    ports:
      - 48888:3306

    expose:
      - 3306

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 40

    volumes:
      - apidb-vol:/var/lib/mysql

    networks:
      _net:
        ipv4_address: 10.5.0.4 
  
  keycloak_db:
    container_name: keycloak_db

    image: postgres
    
    restart: always
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    
    ports:
      - 5555:5432
    
    expose:
      - 5432
    
    volumes:
      - keycloakdb-vol:/var/lib/postgresql/data
    
    networks:
      _net:
        ipv4_address: 10.5.0.5

  keycloak:
    container_name: keycloak

    build:
      context: keycloak
      dockerfile: Dockerfile
    
    ports:
        - 9000:8080
        - 9111:8443
    
    expose:
      - 8080
      - 8443
    
    environment:
      - KC_DB=postgres
      - KC-DB_URL=jdbc:postgresql://10.5.0.5:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=root

      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_HTTP_ENABLED=true

      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    
    command: start-dev --verbose
    
    restart: always

    volumes:
      - keycloak-vol:/opt/keycloak/data/

    networks:
      _net:
        ipv4_address: 10.5.0.6

networks:
  _net:
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  minio-vol:
  elasticsearch-vol:
  kibana-vol:
  api-vol:
  apidb-vol:
  keycloak-vol:
  keycloakdb-vol: